site_name: Starlite
repo_url: https://github.com/starlite-api/starlite
repo_name: starlite-api/starlite
site_url: https://starlite-api.github.io/starlite
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: mirage
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: mirage-light
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  favicon: images/starlite-favicon.ico
  logo: images/2x/starlite-icon@2x.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
  plugins:
    - search:
        lang: en
    - social:
        cards_color:
          fill: "#1d2433"
          text: "#d6dbe1"
        cards_font: Tahoma
extra_css:
  - css/extra.css
nav:
  - Overview:
      - index.md
      - Project Governance: governance.md
      - Contribution Guide: contributing.md
      - License: license.md
  - Usage:
      - The Starlite App:
          - usage/0-the-starlite-app/0-the-starlite-app.md
          - usage/0-the-starlite-app/1-startup-and-shutdown.md
          - usage/0-the-starlite-app/2-using-application-state.md
          - usage/0-the-starlite-app/3-static-files.md
          - usage/0-the-starlite-app/4-logging.md
      - Routing:
          - usage/1-routing/0-routing.md
          - usage/1-routing/1-registering-routes.md
          - usage/1-routing/2-routers.md
          - usage/1-routing/3-controllers.md
          - usage/1-routing/4-registering-components-multiple-times.md
      - Route Handlers:
          - usage/2-route-handlers/0_route_handlers_concept.md
          - usage/2-route-handlers/1_http_route_handlers.md
          - usage/2-route-handlers/2_websocket_route_handlers.md
          - usage/2-route-handlers/3_asgi_route_handlers.md
      - Parameters:
          - usage/3-parameters/0-path-parameters.md
          - usage/3-parameters/1-query-parameters.md
          - usage/3-parameters/2-header-and-cookie-parameters.md
          - usage/3-parameters/3-the-parameter-function.md
          - usage/3-parameters/4-layered-parameters.md
      - Request Data:
          - usage/4-request-data/0-request-data.md
          - usage/4-request-data/1-the-body-function.md
          - usage/4-request-data/2-url-encoded-form-data.md
          - usage/4-request-data/3-multipart-form-data.md
      - Returning Responses:
          - usage/5-responses/0-responses-intro.md
          - usage/5-responses/1-media-type.md
          - usage/5-responses/2-status-codes.md
          - usage/5-responses/3-returning-responses.md
          - usage/5-responses/4-response-headers.md
          - usage/5-responses/5-response-cookies.md
          - usage/5-responses/6-redirect-responses.md
          - usage/5-responses/7-file-responses.md
          - usage/5-responses/8-streaming-responses.md
          - usage/5-responses/9-template-responses.md
          - usage/5-responses/10-custom-responses.md
      - Dependency Injection:
          - usage/6-dependency-injection/0-dependency-injection-intro.md
          - usage/6-dependency-injection/1-dependency-kwargs.md
          - usage/6-dependency-injection/2-overriding-dependencies.md
          - usage/6-dependency-injection/3-the-provide-class.md
          - usage/6-dependency-injection/4-dependencies-in-dependencies.md
          - usage/6-dependency-injection/5-the-dependency-function.md
      - Middleware:
          - usage/7-middleware/0-middleware-intro.md
          - Using Middleware:
              - usage/7-middleware/1-using-middleware/0-using-middleware-intro.md
              - usage/7-middleware/1-using-middleware/1-layering-middleware.md
              - usage/7-middleware/1-using-middleware/2-middleware-call-order.md
              - usage/7-middleware/1-using-middleware/3-define-middleware.md
              - usage/7-middleware/1-using-middleware/4-middleware-and-exceptions.md
          - Creating Middleware:
              - usage/7-middleware/2-creating-middleware/0-creating-middleware-intro.md
              - usage/7-middleware/2-creating-middleware/1-using-basehttp-middleware.md
              - usage/7-middleware/2-creating-middleware/2-using-middleware-protocol.md
          - Builtin Middlewares:
              - usage/7-middleware/3-builtin-middlewares/0-builtin-middlewares-intro.md
              - usage/7-middleware/3-builtin-middlewares/1-cors-middleware.md
              - usage/7-middleware/3-builtin-middlewares/2-trusted-hosts-middleware.md
              - usage/7-middleware/3-builtin-middlewares/3-csrf-middleware.md
              - usage/7-middleware/3-builtin-middlewares/4-compression-middleware.md
      - usage/8-authentication.md
      - usage/9-guards.md
      - Plugins:
          - usage/10-plugins/0-plugins-intro.md
          - usage/10-plugins/1-sql-alchemy-plugin.md
          - usage/10-plugins/2-tortoise-orm-plugin.md
          - usage/10-plugins/3-piccolo-orm-plugin.md
      - usage/11-data-transfer-objects.md
      - usage/12-openapi.md
      - usage/13-lifecycle-hooks.md
      - usage/14-testing.md
      - usage/15-templating.md
      - usage/16-caching.md
      - usage/17-exceptions.md
  - Reference:
      - reference/important.md
      - reference/app.md
      - reference/cache.md
      - reference/config.md
      - reference/connection.md
      - reference/controller.md
      - reference/datastructures.md
      - reference/dto.md
      - reference/exceptions.md
      - reference/enums.md
      - reference/handlers.md
      - reference/logging.md
      - reference/middleware.md
      - reference/openapi.md
      - reference/params.md
      - reference/plugins.md
      - reference/provide.md
      - reference/response.md
      - reference/router.md
      - reference/template.md
      - reference/testing.md
      - reference/types.md
      - reference/typing.md
  - migration.md
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/X3FJqy8d2j
    - icon: fontawesome/brands/github
      link: https://github.com/starlite-api/starlite
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          options:
            heading_level: 3
            members: []
            show_root_heading: true
            show_source: false
            docstring_style: google
            separate_signature: true
            show_if_no_docstring: true
            line_length: 100
watch:
  - starlite
