site_name: Starlite
repo_url: https://github.com/starlite-api/starlite
repo_name: starlite-api/starlite
site_url: https://starlite-api.github.io/starlite
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: mirage
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: mirage-light
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
  favicon: images/starlite-favicon.ico
  logo: images/2x/starlite-icon@2x.png
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - navigation.tracking
    - content.tabs.link
    - search.suggest
    - search.highlight
    - search.share
  plugins:
    - search:
        lang: en
    - social:
        cards_color:
          fill: "#1d2433"
          text: "#d6dbe1"
        cards_font: Tahoma
extra_css:
  - css/typo.css
  - css/color.css
nav:
  - Starlite: index.md
  - Usage:
      - The Starlite App:
          - usage/0-the-starlite-app/0-the-starlite-app.md
          - usage/0-the-starlite-app/1-startup-and-shutdown.md
          - usage/0-the-starlite-app/2-using-application-state.md
          - usage/0-the-starlite-app/3-static-files.md
          - usage/0-the-starlite-app/4-logging.md
          - usage/0-the-starlite-app/5-application-hooks.md
          - usage/0-the-starlite-app/6-application-init-hook.md
      - Routing:
          - usage/1-routing/0-routing.md
          - usage/1-routing/1-registering-routes.md
          - usage/1-routing/2-routers.md
          - usage/1-routing/3-controllers.md
          - usage/1-routing/4-registering-components-multiple-times.md
          - usage/1-routing/5-mounting-asgi-apps.md
      - Route Handlers:
          - usage/2-route-handlers/0-route-handlers-concept.md
          - usage/2-route-handlers/1-http-route-handlers.md
          - usage/2-route-handlers/2-websocket-route-handlers.md
          - usage/2-route-handlers/3-asgi-route-handlers.md
          - usage/2-route-handlers/4-route-handler-indexing.md
          - usage/2-route-handlers/5-handler-opts.md
      - Parameters:
          - usage/3-parameters/0-path-parameters.md
          - usage/3-parameters/1-query-parameters.md
          - usage/3-parameters/2-header-and-cookie-parameters.md
          - usage/3-parameters/3-the-parameter-function.md
          - usage/3-parameters/4-layered-parameters.md
      - Request Data:
          - usage/4-request-data/0-request-data.md
          - usage/4-request-data/1-the-body-function.md
          - usage/4-request-data/2-url-encoded-form-data.md
          - usage/4-request-data/3-multipart-form-data.md
      - Responses:
          - usage/5-responses/0-responses-intro.md
          - usage/5-responses/1-media-type.md
          - usage/5-responses/2-status-codes.md
          - usage/5-responses/3-returning-responses.md
          - usage/5-responses/4-response-headers.md
          - usage/5-responses/5-response-cookies.md
          - usage/5-responses/6-redirect-responses.md
          - usage/5-responses/7-file-responses.md
          - usage/5-responses/8-streaming-responses.md
          - usage/5-responses/9-template-responses.md
          - usage/5-responses/10-custom-responses.md
          - usage/5-responses/11-background-tasks.md
      - Dependency Injection:
          - usage/6-dependency-injection/0-dependency-injection-intro.md
          - usage/6-dependency-injection/1-dependency-kwargs.md
          - usage/6-dependency-injection/2-overriding-dependencies.md
          - usage/6-dependency-injection/3-the-provide-class.md
          - usage/6-dependency-injection/4-dependencies-in-dependencies.md
          - usage/6-dependency-injection/5-the-dependency-function.md
      - Middleware:
          - usage/7-middleware/0-middleware-intro.md
          - Using Middleware:
              - usage/7-middleware/1-using-middleware/0-using-middleware-intro.md
              - usage/7-middleware/1-using-middleware/1-layering-middleware.md
              - usage/7-middleware/1-using-middleware/2-middleware-call-order.md
              - usage/7-middleware/1-using-middleware/3-define-middleware.md
              - usage/7-middleware/1-using-middleware/4-middleware-and-exceptions.md
          - Creating Middleware:
              - usage/7-middleware/2-creating-middleware/0-creating-middleware-intro.md
              - usage/7-middleware/2-creating-middleware/1-using-middleware-protocol.md
              - usage/7-middleware/2-creating-middleware/2-using-abstract-middleware.md
          - Builtin Middlewares:
              - usage/7-middleware/3-builtin-middlewares/0-builtin-middlewares-intro.md
              - usage/7-middleware/3-builtin-middlewares/1-cors-middleware.md
              - usage/7-middleware/3-builtin-middlewares/2-allowed-hosts-middleware.md
              - usage/7-middleware/3-builtin-middlewares/3-csrf-middleware.md
              - usage/7-middleware/3-builtin-middlewares/4-compression-middleware.md
              - usage/7-middleware/3-builtin-middlewares/5-session-middleware.md
              - usage/7-middleware/3-builtin-middlewares/6-rate-limit-middleware.md
              - usage/7-middleware/3-builtin-middlewares/7-logging-middleware.md
      - Security:
          - usage/8-security/0-intro.md
          - usage/8-security/1-abstract-authentication-middleware.md
          - usage/8-security/2-security-backends.md
          - usage/8-security/3-guards.md
      - Testing:
          - usage/9-testing/0-intro.md
          - usage/9-testing/1-test-client.md
          - usage/9-testing/2-create-test-app.md
          - usage/9-testing/3-request-factory.md
          - usage/9-testing/4-pydantic-factories.md
      - Plugins:
          - usage/10-plugins/0-plugins-intro.md
          - usage/10-plugins/1-sql-alchemy-plugin.md
          - usage/10-plugins/2-tortoise-orm-plugin.md
          - usage/10-plugins/3-piccolo-orm-plugin.md
      - Data Transfer Objects:
          - usage/11-data-transfer-objects/0-dto.md
          - usage/11-data-transfer-objects/1-partial.md
      - OpenAPI:
          - usage/12-openapi/0-openapi-intro.md
          - usage/12-openapi/1-schema-generation.md
          - usage/12-openapi/2-route-handler-configuration.md
          - usage/12-openapi/3-openapi-controller.md
          - usage/12-openapi/4-viewing-and-accessing-schema.md
          - usage/12-openapi/5-customizing-pydantic-model-schemas.md
      - usage/13-lifecycle-hooks.md
      - Caching:
          - usage/15-caching/0-cache-backends.md
          - usage/15-caching/1-response-caching.md
          - usage/15-caching/2-interacting-with-cache.md
      - Templates:
          - usage/16-templating/0-template-engines.md
          - usage/16-templating/1-template-context.md
          - usage/16-templating/2-template-functions.md
      - usage/17-exceptions.md
      - Contrib:
          - usage/18-contrib/0-open-telemetry.md
          - usage/18-contrib/1-jwt.md
  - API Reference:
      - reference/0-api-reference-intro.md
      - reference/1-app.md
      - reference/2-router.md
      - reference/3-controller.md
      - reference/5-dto.md
      - reference/6-enums.md
      - Cache:
          - reference/cache/0-base-cache.md
          - reference/cache/1-simple-cache.md
          - reference/cache/2-redis-cache.md
          - reference/cache/3-memcached-cache.md
      - Config:
          - reference/config/0-app-config.md
          - reference/config/1-cache-config.md
          - reference/config/2-cors-config.md
          - reference/config/3-csrf-config.md
          - reference/config/4-compression-config.md
          - reference/config/5-openapi-config.md
          - reference/config/6-static-files-config.md
          - reference/config/7-template-config.md
          - reference/config/8-logging-config.md
          - reference/config/9-allowed-hosts-config.md
      - Connection:
          - reference/connection/0-asgi-connection.md
          - reference/connection/1-request.md
          - reference/connection/2-websocket.md
      - Responses:
          - reference/response/0-base.md
          - reference/response/1-streaming.md
          - reference/response/2-file.md
          - reference/response/3-template.md
          - reference/response/4-redirect.md
      - Datastructures:
          - reference/datastructures/0-state.md
          - reference/datastructures/1-cookie.md
          - reference/datastructures/2-provide.md
          - reference/datastructures/3-headers.md
          - reference/datastructures/4-background.md
          - reference/datastructures/5-response-containers.md
          - reference/datastructures/6-upload-file.md
          - reference/datastructures/7-multi-dicts.md
          - reference/datastructures/8-url.md
      - Exceptions:
          - reference/exceptions/0-base-exceptions.md
          - reference/exceptions/1-http-exceptions.md
          - reference/exceptions/2-websocket-exceptions.md
      - Handlers:
          - reference/handlers/0-base-handler.md
          - reference/handlers/1-http-handlers.md
          - reference/handlers/2-websocket-handlers.md
          - reference/handlers/3-asgi-handlers.md
      - Middleware:
          - reference/middleware/0-base.md
          - reference/middleware/1-authentication-middleware.md
          - reference/middleware/2-logging-middleware.md
          - reference/middleware/3-rate-limit-middleware.md
          - Session Middleware:
              - reference/middleware/session-middleware/0-middleware.md
              - Backends:
                  - reference/middleware/session-middleware/1-base-backend.md
                  - reference/middleware/session-middleware/2-cookie-backend.md
                  - reference/middleware/session-middleware/3-file-backend.md
                  - reference/middleware/session-middleware/4-memcached-backend.md
                  - reference/middleware/session-middleware/5-memory-backend.md
                  - reference/middleware/session-middleware/6-redis-backend.md
                  - reference/middleware/session-middleware/7-sqlalchemy-backend.md
          - reference/middleware/4-compression-middleware.md
          - reference/middleware/5-csrf-middleware.md
          - reference/middleware/6-exceptions-middleware.md
          - reference/middleware/7-cors-middleware.md
      - Security:
          - reference/security/0-base.md
          - reference/security/1-session-auth.md
      - OpenAPI:
          - reference/openapi/0-openapi-controller.md
          - reference/openapi/1-openapi-response-spec.md
      - Parameters:
          - reference/params/0-parameter.md
          - reference/params/1-body.md
          - reference/params/2-dependency.md
      - Plugins:
          - reference/plugins/0-plugin-protocol.md
          - reference/plugins/1-sqlalchemy-plugin.md
          - reference/plugins/2-piccolo-orm-plugin.md
          - reference/plugins/3-tortoise-orm-plugin.md
      - Templating:
          - reference/template/0-base.md
          - reference/template/1-jinja.md
          - reference/template/2-mako.md
      - Testing:
          - reference/testing/0-test-client.md
          - reference/testing/1-request-factory.md
      - Types:
          - reference/types/0-types-intro.md
          - reference/types/1-callable-types.md
          - reference/types/2-asgi-types.md
          - reference/types/3-helper-types.md
          - reference/types/4-protocol-types.md
          - reference/types/5-composite-types.md
          - reference/types/6-partial-types.md
          - reference/types/7-file-types.md
      - Utils:
          - reference/utils/0-predicate-utils.md
          - reference/utils/1-sync-utils.md
          - reference/utils/2-scope-utils.md
          - reference/utils/3-exception-utils.md
          - reference/utils/4-extractor-utils.md
          - reference/utils/5-sequence-utils.md
          - reference/utils/6-path-utils.md
          - reference/utils/7-serialization-utils.md
      - Contrib:
          - reference/contrib/opentelemetry.md
          - reference/contrib/jwt.md
  - migration.md
  - benchmarks.md

extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/X3FJqy8d2j
    - icon: fontawesome/brands/github
      link: https://github.com/starlite-api/starlite
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.magiclink
  - pymdownx.tabbed:
        alternate_style: true
plugins:
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://starlite-api.github.io/pydantic-openapi-schema/objects.inv
            - https://multidict.aio-libs.org/en/stable/objects.inv
          options:
            heading_level: 3
            members: []
            show_root_heading: true
            show_source: false
            docstring_style: google
            separate_signature: true
            show_if_no_docstring: true
            line_length: 100
watch:
  - starlite
  - examples
