name: Documentation Building
on:
  workflow_run:
    workflows: [Tests And Linting]
    branches: [main, v1.51]
    types:
      - completed
  release:
    types: [published]
jobs:
  docs:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'release' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.4.0
          virtualenvs-create: false
          installer-parallel: true
      - name: Install App Dependencies
        run: poetry install --no-interaction --with docs
      - name: Setup gh pages
        run: |
          git fetch origin gh-pages --depth=1
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Deploy to GH-Pages (preview)
        if: ${{ github.event_name != 'release' && github.ref == 'refs/heads/main'}}
        run: python tools/publish_docs.py --version dev --push
      - name: Deploy to GH-Pages (release)
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        run: python tools/publish_docs.py --push
